version: '3.8'

services:
  mongoDB: 
    image: mongo:5.0.25
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
  nodejs_app:
    build: .
    restart: always
    ports:
      - "3000:${PORT}"
    depends_on:
      - mongoDB
    volumes:
      - ./:/data/db